// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt-B9klDI5vFj7aLLMjxyzmFVe8VO6QBQ',
    appId: '1:137369991158:web:9a34c2bedd49647f9139d7',
    messagingSenderId: '137369991158',
    projectId: 'graduation-project-87993',
    authDomain: 'graduation-project-87993.firebaseapp.com',
    storageBucket: 'graduation-project-87993.firebasestorage.app',
    measurementId: 'G-267H2SLBRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SMidNX2lGWhQhB5ntO_2zPzeI8800Ss',
    appId: '1:137369991158:android:d09d99f1e4c52a2a9139d7',
    messagingSenderId: '137369991158',
    projectId: 'graduation-project-87993',
    storageBucket: 'graduation-project-87993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_jtIWBqsbHzXc9TcGbXP5dqFdldH3Do',
    appId: '1:137369991158:ios:054f30d30edefbc19139d7',
    messagingSenderId: '137369991158',
    projectId: 'graduation-project-87993',
    storageBucket: 'graduation-project-87993.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_jtIWBqsbHzXc9TcGbXP5dqFdldH3Do',
    appId: '1:137369991158:ios:054f30d30edefbc19139d7',
    messagingSenderId: '137369991158',
    projectId: 'graduation-project-87993',
    storageBucket: 'graduation-project-87993.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt-B9klDI5vFj7aLLMjxyzmFVe8VO6QBQ',
    appId: '1:137369991158:web:35350111a8a79b1c9139d7',
    messagingSenderId: '137369991158',
    projectId: 'graduation-project-87993',
    authDomain: 'graduation-project-87993.firebaseapp.com',
    storageBucket: 'graduation-project-87993.firebasestorage.app',
    measurementId: 'G-E6ZNBYE3RB',
  );
}
